spring:
  main:
    banner-mode: "off"
    flyway:
      enable: false
      locations: classpath:db/migration

spring.datasource:
  url: jdbc:mysql://localhost:5000/smart
  username: django
  password: 12345

server.port: 8082
server.servlet.context-path: /app